services:
  melodock:
    image: ghcr.io/desilascarvalho/melodock:latest
    container_name: melodock
    restart: unless-stopped
    ports:
      - "9014:9014"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - /path/to/your/music:/music
      - /path/to/your/downloads:/downloads
      - /path/to/your/config:/config